CONST DEFREF_TYPE_LABEL = 1

CONST ERR_ERROR = 3
CONST ERR_FATAL = 4
CONST ERR_INVALID_SYNTAX = 1005
CONST ERR_ENCODING_ISSUE = 1006
CONST ERR_INVALID_UTF8 = 1007

DIM SHARED SinglePassMode AS _BYTE

DIM SHARED CompatVerboseDiagnostics AS _BYTE
DIM SHARED CompatHasErrors AS _BYTE
DIM SHARED CompatErrorCount AS LONG
DIM SHARED CompatMaxErrors AS LONG
DIM SHARED CompatCurrentFile AS STRING
DIM SHARED CompatCurrentPhase AS STRING
DIM SHARED CompatErrorContextDepth AS INTEGER
DIM SHARED CompatErrorContext(1 TO 16) AS STRING
