use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Keyword(Keyword),
    Identifier(String),
    IntegerLiteral(i16),
    LongLiteral(i32),
    SingleLiteral(f32),
    DoubleLiteral(f64),
    StringLiteral(String),
    Plus,
    Minus,
    Multiply,
    Divide,
    IntegerDivide,
    Modulo,
    Power,
    Equal,
    NotEqual,
    LessThan,
    GreaterThan,
    LessOrEqual,
    GreaterOrEqual,
    And,
    Or,
    Not,
    OpenParen,
    CloseParen,
    Comma,
    Semicolon,
    Colon,
    Dollar,
    Ampersand,
    LineContinuation,
    Percent,
    Exclamation,
    Hash,
    Dot,
    Eof,
    Newline,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Keyword {
    If,
    Then,
    Else,
    ElseIf,
    EndIf,
    For,
    To,
    Step,
    Next,
    While,
    Wend,
    Do,
    Loop,
    Until,
    Select,
    Case,
    EndSelect,
    Goto,
    Gosub,
    Return,
    On,
    Error,
    Resume,
    ResumeNext,
    Dim,
    Redim,
    Preserve,
    Common,
    Shared,
    Static,
    DefType,
    DefInt,
    DefStr,
    DefSng,
    DefDbl,
    DefLng,
    Function,
    Sub,
    EndFunction,
    EndSub,
    Type,
    EndType,
    As,
    ByVal,
    ByRef,
    Fn,
    Declare,
    Option,
    OptionBase,
    Base,
    Is,
    Print,
    Input,
    Open,
    Close,
    Get,
    Put,
    Write,
    Line,
    Circle,
    Pset,
    Preset,
    Paint,
    Screen,
    LineInput,
    Sound,
    Play,
    Beep,
    Data,
    Read,
    Restore,
    Let,
    Set,
    Call,
    Randomize,
    Using,
    Tab,
    Spc,
    Locate,
    Cls,
    Absolute,
    Shell,
    End,
    Stop,
    Clear,
    Chain,
    Const,
    Exit,
    Sleep,
    Swap,
    System,
    Timer,
    Eqv,
    Imp,
    Xor,
    Not,
    Mod,
    Output,
    Append,
    Binary,
    Random,
    Access,
    Lock,
    Kill,
    Name,
    Files,
    ChDir,
    MkDir,
    RmDir,
    Field,
    LSet,
    RSet,
    Loc,
    Seek,
    EOF,
    LOF,
    FreeFile,
    Peek,
    Poke,
    Def,
    Seg,
    VarPtr,
    VarSeg,
    Sadd,
    VarPtrStr,
    BLoad,
    BSave,
    Wait,
    Out,
    Inp,
    Stick,
    Point,
    Off,
    Com,
    Pen,
    Strig,
    Key,
    View,
    Window,
    PMap,
    Draw,
    Palette,
    Color,
    Width,
    Hex,
    Oct,
    Mkd,
    Mki,
    Mks,
    Mkl,
    Cvd,
    Cvi,
    Cvs,
    Cvl,
    InKey,
    Date,
    Time,
    Fre,
    Command,
    Environ,
    CsrLin,
    Pos,
    LPrint,
    LPos,
    TrOn,
    TrOff,
    Err,
    Erl,
    ErDev,
    Left,
    Right,
    Mid,
    LCase,
    UCase,
    LTrim,
    RTrim,
    Trim,
    Str,
    Chr,
    Asc,
    Val,
    Len,
    InStr,
    Space,
    String,
    StringFunc,
    InputStr,
    Abs,
    Sgn,
    Atn,
    Cos,
    Exp,
    Fix,
    Int,
    Log,
    Sin,
    Sqr,
    Tan,
    Rnd,
    CInt,
    CLng,
    CSng,
    CDbl,
    CStr,
    UBound,
    LBound,
    Erase,
}

impl Keyword {
    pub fn from_keyword(s: &str) -> Option<Self> {
        match s {
            "IF" => Some(Keyword::If),
            "THEN" => Some(Keyword::Then),
            "ELSE" => Some(Keyword::Else),
            "ELSEIF" => Some(Keyword::ElseIf),
            "ENDIF" => Some(Keyword::EndIf),
            "FOR" => Some(Keyword::For),
            "TO" => Some(Keyword::To),
            "STEP" => Some(Keyword::Step),
            "NEXT" => Some(Keyword::Next),
            "WHILE" => Some(Keyword::While),
            "WEND" => Some(Keyword::Wend),
            "DO" => Some(Keyword::Do),
            "LOOP" => Some(Keyword::Loop),
            "UNTIL" => Some(Keyword::Until),
            "SELECT" => Some(Keyword::Select),
            "CASE" => Some(Keyword::Case),
            "ENDSELECT" => Some(Keyword::EndSelect),
            "GOTO" => Some(Keyword::Goto),
            "GOSUB" => Some(Keyword::Gosub),
            "RETURN" => Some(Keyword::Return),
            "ON" => Some(Keyword::On),
            "ERROR" => Some(Keyword::Error),
            "RESUME" => Some(Keyword::Resume),
            "DIM" => Some(Keyword::Dim),
            "REDIM" => Some(Keyword::Redim),
            "PRESERVE" => Some(Keyword::Preserve),
            "COMMON" => Some(Keyword::Common),
            "SHARED" => Some(Keyword::Shared),
            "STATIC" => Some(Keyword::Static),
            "DEFTYPE" => Some(Keyword::DefType),
            "DEFINT" => Some(Keyword::DefInt),
            "DEFSTR" => Some(Keyword::DefStr),
            "DEFSNG" => Some(Keyword::DefSng),
            "DEFDBL" => Some(Keyword::DefDbl),
            "DEFLNG" => Some(Keyword::DefLng),
            "FUNCTION" => Some(Keyword::Function),
            "SUB" => Some(Keyword::Sub),
            "ENDFUNCTION" => Some(Keyword::EndFunction),
            "ENDSUB" => Some(Keyword::EndSub),
            "TYPE" => Some(Keyword::Type),
            "ENDTYPE" => Some(Keyword::EndType),
            "AS" => Some(Keyword::As),
            "BYVAL" => Some(Keyword::ByVal),
            "BYREF" => Some(Keyword::ByRef),
            "FN" => Some(Keyword::Fn),
            "DECLARE" => Some(Keyword::Declare),
            "OPTION" => Some(Keyword::Option),
            "OPTIONBASE" => Some(Keyword::OptionBase),
            "BASE" => Some(Keyword::Base),
            "IS" => Some(Keyword::Is),
            "PRINT" => Some(Keyword::Print),
            "INPUT" => Some(Keyword::Input),
            "OPEN" => Some(Keyword::Open),
            "CLOSE" => Some(Keyword::Close),
            "GET" => Some(Keyword::Get),
            "PUT" => Some(Keyword::Put),
            "WRITE" => Some(Keyword::Write),
            "LINE" => Some(Keyword::Line),
            "CIRCLE" => Some(Keyword::Circle),
            "PSET" => Some(Keyword::Pset),
            "PRESET" => Some(Keyword::Preset),
            "PAINT" => Some(Keyword::Paint),
            "SCREEN" => Some(Keyword::Screen),
            "LINEINPUT" => Some(Keyword::LineInput),
            "SOUND" => Some(Keyword::Sound),
            "PLAY" => Some(Keyword::Play),
            "BEEP" => Some(Keyword::Beep),
            "DATA" => Some(Keyword::Data),
            "READ" => Some(Keyword::Read),
            "RESTORE" => Some(Keyword::Restore),
            "LET" => Some(Keyword::Let),
            "SET" => Some(Keyword::Set),
            "CALL" => Some(Keyword::Call),
            "RANDOMIZE" => Some(Keyword::Randomize),
            "USING" => Some(Keyword::Using),
            "TAB" => Some(Keyword::Tab),
            "SPC" => Some(Keyword::Spc),
            "LOCATE" => Some(Keyword::Locate),
            "CLS" => Some(Keyword::Cls),
            "ABSOLUTE" => Some(Keyword::Absolute),
            "SHELL" => Some(Keyword::Shell),
            "END" => Some(Keyword::End),
            "STOP" => Some(Keyword::Stop),
            "CLEAR" => Some(Keyword::Clear),
            "CHAIN" => Some(Keyword::Chain),
            "CONST" => Some(Keyword::Const),
            "EXIT" => Some(Keyword::Exit),
            "SLEEP" => Some(Keyword::Sleep),
            "SWAP" => Some(Keyword::Swap),
            "SYSTEM" => Some(Keyword::System),
            "TIMER" => Some(Keyword::Timer),
            "EQV" => Some(Keyword::Eqv),
            "IMP" => Some(Keyword::Imp),
            "XOR" => Some(Keyword::Xor),
            "MOD" => Some(Keyword::Mod),
            "OUTPUT" => Some(Keyword::Output),
            "APPEND" => Some(Keyword::Append),
            "BINARY" => Some(Keyword::Binary),
            "RANDOM" => Some(Keyword::Random),
            "ACCESS" => Some(Keyword::Access),
            "LOCK" => Some(Keyword::Lock),
            "KILL" => Some(Keyword::Kill),
            "NAME" => Some(Keyword::Name),
            "FILES" => Some(Keyword::Files),
            "CHDIR" => Some(Keyword::ChDir),
            "MKDIR" => Some(Keyword::MkDir),
            "RMDIR" => Some(Keyword::RmDir),
            "FIELD" => Some(Keyword::Field),
            "LSET" => Some(Keyword::LSet),
            "RSET" => Some(Keyword::RSet),
            "LOC" => Some(Keyword::Loc),
            "SEEK" => Some(Keyword::Seek),
            "EOF" => Some(Keyword::EOF),
            "LOF" => Some(Keyword::LOF),
            "FREEFILE" => Some(Keyword::FreeFile),
            "PEEK" => Some(Keyword::Peek),
            "POKE" => Some(Keyword::Poke),
            "DEF" => Some(Keyword::Def),
            "SEG" => Some(Keyword::Seg),
            "VARPTR" => Some(Keyword::VarPtr),
            "VARSEG" => Some(Keyword::VarSeg),
            "SADD" => Some(Keyword::Sadd),
            "VARPTRSTR" => Some(Keyword::VarPtrStr),
            "BLOAD" => Some(Keyword::BLoad),
            "BSAVE" => Some(Keyword::BSave),
            "WAIT" => Some(Keyword::Wait),
            "OUT" => Some(Keyword::Out),
            "INP" => Some(Keyword::Inp),
            "STICK" => Some(Keyword::Stick),
            "POINT" => Some(Keyword::Point),
            "OFF" => Some(Keyword::Off),
            "COM" => Some(Keyword::Com),
            "PEN" => Some(Keyword::Pen),
            "STRIG" => Some(Keyword::Strig),
            "KEY" => Some(Keyword::Key),
            "VIEW" => Some(Keyword::View),
            "WINDOW" => Some(Keyword::Window),
            "PMAP" => Some(Keyword::PMap),
            "DRAW" => Some(Keyword::Draw),
            "PALETTE" => Some(Keyword::Palette),
            "COLOR" => Some(Keyword::Color),
            "WIDTH" => Some(Keyword::Width),
            "HEX" => Some(Keyword::Hex),
            "OCT" => Some(Keyword::Oct),
            "MKD" => Some(Keyword::Mkd),
            "MKI" => Some(Keyword::Mki),
            "MKS" => Some(Keyword::Mks),
            "MKL" => Some(Keyword::Mkl),
            "CVD" => Some(Keyword::Cvd),
            "CVI" => Some(Keyword::Cvi),
            "CVS" => Some(Keyword::Cvs),
            "CVL" => Some(Keyword::Cvl),
            "INKEY" => Some(Keyword::InKey),
            "DATE" => Some(Keyword::Date),
            "TIME" => Some(Keyword::Time),
            "FRE" => Some(Keyword::Fre),
            "COMMAND" => Some(Keyword::Command),
            "ENVIRON" => Some(Keyword::Environ),
            "CSRLIN" => Some(Keyword::CsrLin),
            "POS" => Some(Keyword::Pos),
            "LPRINT" => Some(Keyword::LPrint),
            "LPOS" => Some(Keyword::LPos),
            "TRON" => Some(Keyword::TrOn),
            "TROFF" => Some(Keyword::TrOff),
            "ERR" => Some(Keyword::Err),
            "ERL" => Some(Keyword::Erl),
            "ERDEV" => Some(Keyword::ErDev),
            "LEFT" => Some(Keyword::Left),
            "RIGHT" => Some(Keyword::Right),
            "MID" => Some(Keyword::Mid),
            "LCASE" => Some(Keyword::LCase),
            "UCASE" => Some(Keyword::UCase),
            "LTRIM" => Some(Keyword::LTrim),
            "RTRIM" => Some(Keyword::RTrim),
            "TRIM" => Some(Keyword::Trim),
            "STR" => Some(Keyword::Str),
            "CHR" => Some(Keyword::Chr),
            "ASC" => Some(Keyword::Asc),
            "VAL" => Some(Keyword::Val),
            "LEN" => Some(Keyword::Len),
            "INSTR" => Some(Keyword::InStr),
            "SPACE" => Some(Keyword::Space),
            "STRING" => Some(Keyword::String),
            "ABS" => Some(Keyword::Abs),
            "SGN" => Some(Keyword::Sgn),
            "ATN" => Some(Keyword::Atn),
            "COS" => Some(Keyword::Cos),
            "EXP" => Some(Keyword::Exp),
            "FIX" => Some(Keyword::Fix),
            "INT" => Some(Keyword::Int),
            "LOG" => Some(Keyword::Log),
            "SIN" => Some(Keyword::Sin),
            "SQR" => Some(Keyword::Sqr),
            "TAN" => Some(Keyword::Tan),
            "RND" => Some(Keyword::Rnd),
            "CINT" => Some(Keyword::CInt),
            "CLNG" => Some(Keyword::CLng),
            "CSNG" => Some(Keyword::CSng),
            "CDBL" => Some(Keyword::CDbl),
            "CSTR" => Some(Keyword::CStr),
            "UBOUND" => Some(Keyword::UBound),
            "LBOUND" => Some(Keyword::LBound),
            "ERASE" => Some(Keyword::Erase),
            _ => None,
        }
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Token::Keyword(kw) => write!(f, "{:?}", kw),
            Token::Identifier(s) => write!(f, "Identifier({})", s),
            Token::IntegerLiteral(n) => write!(f, "Integer({})", n),
            Token::LongLiteral(n) => write!(f, "Long({})", n),
            Token::SingleLiteral(n) => write!(f, "Single({})", n),
            Token::DoubleLiteral(n) => write!(f, "Double({})", n),
            Token::StringLiteral(s) => write!(f, "String(\"{}\")", s),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Multiply => write!(f, "*"),
            Token::Divide => write!(f, "/"),
            Token::IntegerDivide => write!(f, "\\"),
            Token::Modulo => write!(f, "MOD"),
            Token::Power => write!(f, "^"),
            Token::Equal => write!(f, "="),
            Token::NotEqual => write!(f, "<>"),
            Token::LessThan => write!(f, "<"),
            Token::GreaterThan => write!(f, ">"),
            Token::LessOrEqual => write!(f, "<="),
            Token::GreaterOrEqual => write!(f, ">="),
            Token::And => write!(f, "AND"),
            Token::Or => write!(f, "OR"),
            Token::Not => write!(f, "NOT"),
            Token::OpenParen => write!(f, "("),
            Token::CloseParen => write!(f, ")"),
            Token::Comma => write!(f, ","),
            Token::Semicolon => write!(f, ";"),
            Token::Colon => write!(f, ":"),
            Token::Dollar => write!(f, "$"),
            Token::Ampersand => write!(f, "&"),
            Token::LineContinuation => write!(f, "_"),
            Token::Percent => write!(f, "%"),
            Token::Exclamation => write!(f, "!"),
            Token::Hash => write!(f, "#"),
            Token::Dot => write!(f, "."),
            Token::Eof => write!(f, "EOF"),
            Token::Newline => write!(f, "\\n"),
        }
    }
}
