DIM SHARED GL_COMMAND_CN(2000) AS STRING * 64
DIM SHARED GL_COMMAND_SUBFUNC(2000) AS INTEGER
DIM SHARED GL_COMMAND_CALLNAME(2000) AS STRING * 64
DIM SHARED GL_COMMAND_ARGS(2000) AS INTEGER
DIM SHARED GL_COMMAND_ARG(2000) AS STRING * 80
DIM SHARED GL_COMMAND_RET(2000) AS LONG
DIM SHARED GL_HELPER_CODE AS STRING
DIM SHARED GL_COMMANDS_LAST
DIM SHARED GL_DEFINES(2000) AS STRING 'average ~600 entries
DIM SHARED GL_DEFINES_VALUE(2000) AS _INTEGER64
DIM SHARED GL_DEFINES_LAST
DIM SHARED GL_KIT: GL_KIT = 0
