DIM FIRED AS INTEGER
DIM START! AS SINGLE
FIRED = -1
START! = TIMER
ON PLAY(2) GOSUB Hit
PLAY ON
PLAY "MBT120MLL8CCCR"
DO WHILE (PLAY(0) > 0 OR FIRED < 0) AND TIMER < START! + 5
LOOP
PRINT FIRED
PRINT PLAY(0)
END
Hit:
FIRED = PLAY(0)
PLAY OFF
RETURN
