'===============================================================================
' QBNex Code Generator Module
'===============================================================================
' Transpiles BASIC AST to C++ code with runtime library calls.
' Generates optimized C++ code that links with libqb runtime.
'===============================================================================

'-------------------------------------------------------------------------------
' CODE GENERATOR STATE
'-------------------------------------------------------------------------------

TYPE CodeGenState
    outputFile AS INTEGER
    tempFile AS INTEGER
    indentLevel AS INTEGER
    currentLine AS LONG
    inFunction AS _BYTE
    inSub AS _BYTE
    functionName AS STRING * 256
    labelCount AS LONG
    tempVarCount AS LONG
    stringPoolSize AS LONG
END TYPE

DIM SHARED CodeGen AS CodeGenState
DIM SHARED OutputBuffer(1 TO 10000) AS STRING
DIM SHARED OutputLineCount AS LONG
DIM SHARED StringPool(1 TO 1000) AS STRING
DIM SHARED StringPoolCount AS INTEGER

'-------------------------------------------------------------------------------
' C++ CODE TEMPLATES
'-------------------------------------------------------------------------------

CONST HEADER_TEMPLATE = "#include <iostream>~#include <string>~#include <cmath>~#include \"libqb.h\"~"
CONST MAIN_TEMPLATE = "int main(int argc, char* argv[]) {~    qb_init();~    $BODY~    qb_cleanup();~    return 0;~}"

'-------------------------------------------------------------------------------
' INITIALIZATION AND CLEANUP
'-------------------------------------------------------------------------------

SUB InitCodeGenerator
    CodeGen.outputFile = 0
    CodeGen.tempFile = 0
    CodeGen.indentLevel = 0
    CodeGen.currentLine = 0
    CodeGen.inFunction = 0
    CodeGen.inSub = 0
    CodeGen.functionName = ""
    CodeGen.labelCount = 0
    CodeGen.tempVarCount = 0
    CodeGen.stringPoolSize = 0
    
    OutputLineCount = 0
    StringPoolCount = 0
END SUB

SUB CleanupCodeGenerator
    ' Close any open files
    IF CodeGen.outputFile > 0 THEN
        CLOSE #CodeGen.outputFile
        CodeGen.outputFile = 0
    END IF
    
    IF CodeGen.tempFile > 0 THEN
        CLOSE #CodeGen.tempFile
        CodeGen.tempFile = 0
    END IF
    
    OutputLineCount = 0
END SUB

'-------------------------------------------------------------------------------
' OUTPUT MANAGEMENT
'-------------------------------------------------------------------------------

SUB SetOutputFile (fileName AS STRING)
    IF CodeGen.outputFile > 0 THEN CLOSE #CodeGen.outputFile
    
    CodeGen.outputFile = FREEFILE
    OPEN fileName FOR OUTPUT AS #CodeGen.outputFile
END SUB

SUB SetTempFile (fileName AS STRING)
    IF CodeGen.tempFile > 0 THEN CLOSE #CodeGen.tempFile
    
    CodeGen.tempFile = FREEFILE
    OPEN fileName FOR OUTPUT AS #CodeGen.tempFile
END SUB

SUB EmitLine (lineText AS STRING)
    DIM i AS INTEGER
    DIM indent AS STRING
    
    ' Build indentation
    indent = ""
    FOR i = 1 TO CodeGen.indentLevel
        indent = indent + "    "
    NEXT
    
    ' Add to output buffer
    IF OutputLineCount < 10000 THEN
        OutputLineCount = OutputLineCount + 1
        OutputBuffer(OutputLineCount) = indent + lineText
    END IF
    
    ' Also write to file if open
    IF CodeGen.outputFile > 0 THEN
        PRINT #CodeGen.outputFile, indent + lineText
    END IF
END SUB

SUB EmitBlankLine
    EmitLine ""
END SUB

SUB IncreaseIndent
    CodeGen.indentLevel = CodeGen.indentLevel + 1
END SUB

SUB DecreaseIndent
    IF CodeGen.indentLevel > 0 THEN
        CodeGen.indentLevel = CodeGen.indentLevel - 1
    END IF
END SUB

'-------------------------------------------------------------------------------
' CODE GENERATION - HEADER
'-------------------------------------------------------------------------------

SUB GenerateHeader
    EmitLine "// Generated by QBNex Compiler"
    EmitLine "// DO NOT EDIT - This file is auto-generated"
    EmitBlankLine
    
    ' Include standard headers
    EmitLine "#include <iostream>"
    EmitLine "#include <string>"
    EmitLine "#include <cmath>"
    EmitLine "#include <vector>"
    EmitLine "#include <cstdint>"
    EmitBlankLine
    
    ' Include QBNex runtime
    EmitLine "#include \"libqb.h\""
    EmitBlankLine
    
    ' Forward declarations
    GenerateForwardDeclarations
    
    EmitBlankLine
END SUB

SUB GenerateForwardDeclarations
    ' Would iterate through symbol table and generate function prototypes
    EmitLine "// Forward declarations"
    ' Example:
    ' EmitLine "void mySub();"
    ' EmitLine "int32_t myFunction(int32_t param);"
END SUB

'-------------------------------------------------------------------------------
' CODE GENERATION - MAIN
'-------------------------------------------------------------------------------

SUB GenerateMainFunction (astRoot AS LONG)
    EmitLine "int main(int argc, char* argv[]) {"
    IncreaseIndent
    
    EmitLine "// Initialize QBNex runtime"
    EmitLine "qb_init();"
    EmitBlankLine
    
    ' Generate code for main program body
    ' This would traverse the AST and generate statements
    GenerateStatements astRoot
    
    EmitBlankLine
    EmitLine "// Cleanup QBNex runtime"
    EmitLine "qb_cleanup();"
    EmitLine "return 0;"
    
    DecreaseIndent
    EmitLine "}"
END SUB

'-------------------------------------------------------------------------------
' CODE GENERATION - STATEMENTS
'-------------------------------------------------------------------------------

SUB GenerateStatements (nodeIndex AS LONG)
    ' Would traverse AST and generate corresponding C++ code
    ' This is a simplified placeholder
    
    EmitLine "// Generated statements would go here"
    EmitLine "// (Full implementation would traverse the AST)"
END SUB

SUB GenerateVariableDeclaration (varName AS STRING, varType AS INTEGER, isArray AS _BYTE, arrayDims AS INTEGER)
    DIM typeStr AS STRING
    typeStr = QBTypeToCPP$(varType)
    
    IF isArray THEN
        ' Generate array declaration
        EmitLine typeStr + " " + varName + "_array[" + STR$(arrayDims) + "];"
    ELSE
        ' Generate scalar declaration
        EmitLine typeStr + " " + varName + ";"
    END IF
END SUB

SUB GenerateAssignment (target AS STRING, value AS STRING, targetType AS INTEGER)
    EmitLine target + " = " + value + ";"
END SUB

SUB GenerateIfStatement (condition AS STRING, thenBody AS LONG, elseBody AS LONG)
    EmitLine "if (" + condition + ") {"
    IncreaseIndent
    
    ' Generate then body
    GenerateStatements thenBody
    
    DecreaseIndent
    
    IF elseBody > 0 THEN
        EmitLine "} else {"
        IncreaseIndent
        
        ' Generate else body
        GenerateStatements elseBody
        
        DecreaseIndent
    END IF
    
    EmitLine "}"
END SUB

SUB GenerateForLoop (loopVar AS STRING, startVal AS STRING, endVal AS STRING, stepVal AS STRING)
    EmitLine "for (" + loopVar + " = " + startVal + "; " + loopVar + " <= " + endVal + "; " + loopVar + " += " + stepVal + ") {"
    IncreaseIndent
END SUB

SUB GenerateNextStatement
    DecreaseIndent
    EmitLine "}"
END SUB

SUB GenerateWhileLoop (condition AS STRING)
    EmitLine "while (" + condition + ") {"
    IncreaseIndent
END SUB

SUB GenerateWendStatement
    DecreaseIndent
    EmitLine "}"
END SUB

SUB GenerateDoLoop (isUntil AS _BYTE, condition AS STRING)
    IF isUntil THEN
        EmitLine "do {"
        IncreaseIndent
    ELSE
        EmitLine "while (" + condition + ") {"
        IncreaseIndent
    END IF
END SUB

SUB GenerateLoopStatement (isUntil AS _BYTE, condition AS STRING)
    DecreaseIndent
    
    IF isUntil THEN
        EmitLine "} while (!(" + condition + "));"
    ELSE
        EmitLine "}"
    END IF
END SUB

SUB GenerateSelectCase (selectExpr AS STRING)
    EmitLine "switch (" + selectExpr + ") {"
    IncreaseIndent
END SUB

SUB GenerateCase (caseValue AS STRING)
    DecreaseIndent
    EmitLine "case " + caseValue + ":"
    IncreaseIndent
END SUB

SUB GenerateCaseElse
    DecreaseIndent
    EmitLine "default:"
    IncreaseIndent
END SUB

SUB GenerateEndSelect
    DecreaseIndent
    EmitLine "}"
END SUB

SUB GenerateGoto (labelName AS STRING)
    EmitLine "goto " + labelName + ";"
END SUB

SUB GenerateLabel (labelName AS STRING)
    DecreaseIndent
    EmitLine labelName + ":"
    IncreaseIndent
END SUB

SUB GenerateGosub (subName AS STRING)
    EmitLine "gosub_" + subName + "();"
END SUB

SUB GenerateReturn
    IF CodeGen.inFunction THEN
        EmitLine "return result;"
    ELSEIF CodeGen.inSub THEN
        EmitLine "return;"
    ELSE
        EmitLine "return;"
    END IF
END SUB

SUB GenerateExit (exitType AS STRING)
    SELECT CASE UCASE$(exitType)
        CASE "SUB"
            EmitLine "return;"
        CASE "FUNCTION"
            EmitLine "return result;"
        CASE "FOR", "DO", "WHILE"
            EmitLine "break;"
    END SELECT
END SUB

'-------------------------------------------------------------------------------
' CODE GENERATION - SUB/FUNCTION
'-------------------------------------------------------------------------------

SUB GenerateSubDefinition (subName AS STRING)
    CodeGen.inSub = -1
    CodeGen.inFunction = 0
    CodeGen.functionName = subName
    
    EmitLine "void " + subName + "() {"
    IncreaseIndent
END SUB

SUB GenerateFunctionDefinition (funcName AS STRING, returnType AS INTEGER)
    DIM typeStr AS STRING
    typeStr = QBTypeToCPP$(returnType)
    
    CodeGen.inSub = 0
    CodeGen.inFunction = -1
    CodeGen.functionName = funcName
    
    EmitLine typeStr + " " + funcName + "() {"
    IncreaseIndent
    
    ' Declare result variable
    EmitLine typeStr + " result;"
END SUB

SUB GenerateEndSub
    DecreaseIndent
    EmitLine "}"
    
    CodeGen.inSub = 0
    CodeGen.functionName = ""
END SUB

SUB GenerateEndFunction
    EmitLine "return result;"
    DecreaseIndent
    EmitLine "}"
    
    CodeGen.inFunction = 0
    CodeGen.functionName = ""
END SUB

SUB GenerateCall (subName AS STRING)
    EmitLine subName + "();"
END SUB

SUB GenerateFunctionCall (funcName AS STRING, args AS STRING, assignTarget AS STRING)
    IF assignTarget = "" THEN
        EmitLine funcName + "(" + args + ");"
    ELSE
        EmitLine assignTarget + " = " + funcName + "(" + args + ");"
    END IF
END SUB

'-------------------------------------------------------------------------------
' CODE GENERATION - I/O
'-------------------------------------------------------------------------------

SUB GeneratePrint (exprList AS STRING, isNewLine AS _BYTE)
    IF isNewLine THEN
        EmitLine "std::cout << " + exprList + " << std::endl;"
    ELSE
        EmitLine "std::cout << " + exprList + ";"
    END IF
END SUB

SUB GenerateInput (prompt AS STRING, varList AS STRING)
    IF prompt <> "" THEN
        EmitLine "std::cout << " + CppStringLiteral$(prompt) + ";"
    END IF
    EmitLine "std::cin >> " + varList + ";"
END SUB

SUB GenerateFileOpen (fileNum AS STRING, fileName AS STRING, mode AS STRING)
    EmitLine "// File open: " + fileName + " as #" + fileNum
END SUB

SUB GenerateFileClose (fileNum AS STRING)
    EmitLine "// File close #" + fileNum
END SUB

SUB GenerateFileWrite (fileNum AS STRING, dataExpr AS STRING)
    EmitLine "// Write to file #" + fileNum
END SUB

SUB GenerateFileRead (fileNum AS STRING, varName AS STRING)
    EmitLine "// Read from file #" + fileNum
END SUB

'-------------------------------------------------------------------------------
' CODE GENERATION - EXPRESSIONS
'-------------------------------------------------------------------------------

FUNCTION QBTypeToCPP$ (qbType AS INTEGER)
    SELECT CASE qbType
        CASE TYPE_INTEGER: QBTypeToCPP$ = "int16_t"
        CASE TYPE_LONG: QBTypeToCPP$ = "int32_t"
        CASE TYPE_SINGLE: QBTypeToCPP$ = "float"
        CASE TYPE_DOUBLE: QBTypeToCPP$ = "double"
        CASE TYPE_STRING: QBTypeToCPP$ = "std::string"
        CASE TYPE_BYTE: QBTypeToCPP$ = "int8_t"
        CASE TYPE_INTEGER64: QBTypeToCPP$ = "int64_t"
        CASE TYPE_FLOAT: QBTypeToCPP$ = "long double"
        CASE TYPE_VARIANT: QBTypeToCPP$ = "qb_variant_t"
        CASE ELSE: QBTypeToCPP$ = "int32_t"
    END SELECT
END FUNCTION

FUNCTION QBOperatorToCPP$ (qbOp AS STRING)
    SELECT CASE UCASE$(qbOp)
        CASE "=": QBOperatorToCPP$ = "=="
        CASE "<>": QBOperatorToCPP$ = "!="
        CASE "AND": QBOperatorToCPP$ = "&&"
        CASE "OR": QBOperatorToCPP$ = "||"
        CASE "NOT": QBOperatorToCPP$ = "!"
        CASE "XOR": QBOperatorToCPP$ = "^"
        CASE "MOD": QBOperatorToCPP$ = "%"
        CASE "\\": QBOperatorToCPP$ = "/"
        CASE ELSE: QBOperatorToCPP$ = qbOp
    END SELECT
END FUNCTION

FUNCTION CppStringLiteral$ (strVal AS STRING)
    ' Escape special characters for C++ string
    DIM result AS STRING
    DIM i AS INTEGER
    DIM ch AS STRING
    
    result = CHR$(34)
    
    FOR i = 1 TO LEN(strVal)
        ch = MID$(strVal, i, 1)
        SELECT CASE ch
            CASE CHR$(34): result = result + "\\\""
            CASE "\\": result = result + "\\\\"
            CASE CHR$(10): result = result + "\\n"
            CASE CHR$(13): result = result + "\\r"
            CASE CHR$(9): result = result + "\\t"
            CASE ELSE: result = result + ch
        END SELECT
    NEXT
    
    result = result + CHR$(34)
    CppStringLiteral$ = result
END FUNCTION

SUB GenerateExpression (expr AS STRING)
    ' Would generate C++ expression from AST
    EmitLine expr + ";"
END SUB

'-------------------------------------------------------------------------------
' STRING POOL OPTIMIZATION
'-------------------------------------------------------------------------------

FUNCTION AddStringToPool% (strVal AS STRING)
    DIM i AS INTEGER
    
    ' Check if already in pool
    FOR i = 1 TO StringPoolCount
        IF StringPool(i) = strVal THEN
            AddStringToPool% = i
            EXIT FUNCTION
        END IF
    NEXT
    
    ' Add to pool
    IF StringPoolCount < 1000 THEN
        StringPoolCount = StringPoolCount + 1
        StringPool(StringPoolCount) = strVal
        AddStringToPool% = StringPoolCount
    ELSE
        AddStringToPool% = 0
    END IF
END FUNCTION

SUB GenerateStringPool
    DIM i AS INTEGER
    
    IF StringPoolCount = 0 THEN EXIT SUB
    
    EmitLine "// String pool"
    
    FOR i = 1 TO StringPoolCount
        EmitLine "const char* str_pool_" + LTRIM$(STR$(i)) + " = " + CppStringLiteral$(StringPool(i)) + ";"
    NEXT
    
    EmitBlankLine
END SUB

'-------------------------------------------------------------------------------
' MAIN CODE GENERATION ENTRY POINT
'-------------------------------------------------------------------------------

SUB GenerateCodeFromAST (astRoot AS LONG, outputFile AS STRING)
    ' Set output file
    SetOutputFile outputFile
    
    ' Generate header
    GenerateHeader
    
    ' Generate string pool
    GenerateStringPool
    
    ' Generate main function
    GenerateMainFunction astRoot
    
    ' Generate any additional functions/subs
    ' (Would iterate through symbol table)
    
    ' Close output file
    IF CodeGen.outputFile > 0 THEN
        CLOSE #CodeGen.outputFile
        CodeGen.outputFile = 0
    END IF
END SUB

FUNCTION GetOutputLineCount%
    GetOutputLineCount% = OutputLineCount
END FUNCTION

SUB PrintGeneratedCode
    DIM i AS LONG
    FOR i = 1 TO OutputLineCount
        PRINT OutputBuffer(i)
    NEXT
END SUB
