name: Pull Request CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt update && sudo apt install libglu1-mesa-dev libncurses-dev
    - name: Build compiler
      run: QBNEX_CI=1 bash ./setup_lnx.sh
